# Generated by Django 5.2.4 on 2025-08-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="User",
        ),
    ]
