# Generated by Django 5.2.4 on 2025-08-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_remove_shippingaddress_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address",
            new_name="shipping_address",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="city",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="country",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="full_name",
            new_name="shipping_full_name",
        ),
    ]
